In [2]:
#https://www.w3schools.com/python/python_ml_decision_tree.asp

### Machine Learning Lab3: Created by Jibrael Jos,PhD
### Topic: SVM Explorations
### Student Name: Naveen Krishna
### Roll No:23122023
### Date: 15 March
### Submission : 4th April

In [3]:
import pandas

df = pandas.read_csv("cancerAllv3.csv")

print(df)

     radius  texture  perimeter    area        s        c  concavity       cp  \
0     17.99    10.38     122.80  1001.0  0.11840  0.27760    0.30010  0.14710   
1     20.57    17.77     132.90  1326.0  0.08474  0.07864    0.08690  0.07017   
2     19.69    21.25     130.00  1203.0  0.10960  0.15990    0.19740  0.12790   
3     11.42    20.38      77.58   386.1  0.14250  0.28390    0.24140  0.10520   
4     20.29    14.34     135.10  1297.0  0.10030  0.13280    0.19800  0.10430   
..      ...      ...        ...     ...      ...      ...        ...      ...   
564   21.56    22.39     142.00  1479.0  0.11100  0.11590    0.24390  0.13890   
565   20.13    28.25     131.20  1261.0  0.09780  0.10340    0.14400  0.09791   
566   16.60    28.08     108.30   858.1  0.08455  0.10230    0.09251  0.05302   
567   20.60    29.33     140.10  1265.0  0.11780  0.27700    0.35140  0.15200   
568    7.76    24.54      47.92   181.0  0.05263  0.04362    0.00000  0.00000   

        sym       fd  ...  

In [4]:

features=['radius','texture','perimeter','area','s','c','concavity','cp','sym']
          
import numpy as np
X = np.array(df)
y = X[:,30]
X = X[:,0:9]

print(X)
print(y)

[[1.799e+01 1.038e+01 1.228e+02 ... 3.001e-01 1.471e-01 2.419e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 8.690e-02 7.017e-02 1.812e-01]
 [1.969e+01 2.125e+01 1.300e+02 ... 1.974e-01 1.279e-01 2.069e-01]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 9.251e-02 5.302e-02 1.590e-01]
 [2.060e+01 2.933e+01 1.401e+02 ... 3.514e-01 1.520e-01 2.397e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 0.000e+00 1.587e-01]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0.
 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.
 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1.
 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 0. 1. 1

In [5]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y , 
                                   random_state=104,  
                                   test_size=0.25,  
                                   shuffle=True)

In [6]:
import pandas
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

from sklearn.svm import SVC 
clf = SVC(kernel='linear') 

# fitting x samples and y classes 
clf.fit(X_train, y_train) 


SVC(kernel='linear')

#### Accuracy for training dataset.

In [7]:
from sklearn.metrics import accuracy_score
predicted = clf.predict(X_train)
print (accuracy_score(y_train, predicted))

0.9225352112676056


#### Accuracy for testing dataset.

In [8]:
from sklearn.metrics import accuracy_score
predicted = clf.predict(X_test)
print (accuracy_score(y_test, predicted))

0.9020979020979021


## Classification Report

In [10]:
from sklearn.metrics import classification_report
features=['radius','texture','perimeter','area','s','c','concavity','cp','sym']
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.91      0.93      0.92        87
         1.0       0.89      0.86      0.87        56

    accuracy                           0.90       143
   macro avg       0.90      0.89      0.90       143
weighted avg       0.90      0.90      0.90       143



## Confussion Matrix

In [11]:
from sklearn.metrics import confusion_matrix



conf_matrix = confusion_matrix(y_test, y_pred)

print( conf_matrix)

[[81  6]
 [ 8 48]]


## Grid Search

In [9]:

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC


# Define the parameter grid to search
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': [ 'linear', 'poly']
}

# Create a grid search object
grid_search = GridSearchCV(SVC(), param_grid, cv=5)

# Perform grid search on the training data
grid_search.fit(X_train, y_train)

# Get the best hyperparameters and model
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# Evaluate the best model on the test set
accuracy = best_model.score(X_test, y_test)

print("Best hyperparameters:", best_params)
print("Test set accuracy:", accuracy)

Best hyperparameters: {'C': 10, 'kernel': 'linear'}
Test set accuracy: 0.9090909090909091
