# Data Preprocessing

In [521]:
# Importing necessery packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

df = pd.read_csv('Data.csv')
df

surgery  age  hospital_number rectal_temperature pulse respiratory_rate  \
0         1    1           534817               39.2    88               20   
1         2    1           530334               38.3    40               24   
2         1    9          5290409               39.1   164               84   
3         2    1           530255               37.3   104               35   
4         2    1           528355                  ?     ?                ?   
..      ...  ...              ...                ...   ...              ...   
288       1    1           529126                 38    50               36   
289       2    1           535054               38.6    45               16   
290       1    1           528890               38.9    80               44   
291       1    1           530034                 37    66               20   
292       1    1           534004                  ?    78               24   

    temperature_of_extremities peripheral_pulse capillary_refill_time pain  \
0                            ?                ?                     1    3   
1                            1                1                     1    3   
2                            4                1                     2    2   
3                            ?                ?                     2    ?   
4                            2                1                     1    2   
..                         ...              ...                   ...  ...   
288                          ?                1                     1    3   
289                          2                1                     1    1   
290                          3                3                     1    2   
291                          1                3                     1    4   
292                          3                3                     1    ?   

     ... rectal_examination_feces packed_cell_volume total_protein  \
0    ...                        4                 50            85   
1    ...                        1                 33           6.7   
2    ...                        3                 48           7.2   
3    ...                        ?                 74           7.4   
4    ...                        3                  ?             ?   
..   ...                      ...                ...           ...   
288  ...                        3                 39           6.6   
289  ...                        1                 43            58   
290  ...                        3                 54           6.5   
291  ...                        1                 35           6.9   
292  ...                        ?                 43            62   

    abdominocentesis_total_protein lesion_site lesion_type lesion_subtype  \
0                                2        2208           0              0   
1                                ?           0           0              0   
2                              5.3        2208           0              0   
3                                ?        4300           0              0   
4                                ?           0           0              0   
..                             ...         ...         ...            ...   
288                            5.3        8400           0              0   
289                              ?           0           0              0   
290                              ?        7111           0              0   
291                              ?       31110           0              0   
292                              2        2209           0              0   

    PossibleY PossibleY2  PossibleY3  
0           2          3           2  
1           1          1           2  
2           1          2           1  
3           2          2           2  
4           2          1           2  
..        ...        ...         ...  
288         1          1           1  
289         2          1           2  
2

In [522]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   surgery                         293 non-null    object
 1   age                             293 non-null    int64 
 2   hospital_number                 293 non-null    int64 
 3   rectal_temperature              293 non-null    object
 4   pulse                           293 non-null    object
 5   respiratory_rate                293 non-null    object
 6   temperature_of_extremities      293 non-null    object
 7   peripheral_pulse                293 non-null    object
 8   capillary_refill_time           293 non-null    object
 9   pain                            293 non-null    object
 10  peristalsis                     293 non-null    object
 11  abdominal_distension            293 non-null    object
 12  nasogastric_tube                293 non-null    ob

Since most of the columns are showing as objects and we can see that all the columns of the dataset is  in numerical. So we came to know that the missing values are represented in some kind of special character. '?' So we have to replace those '?' with NaN values first and then process with the null values

In [523]:
df = df.replace('?', np.NaN)
df

surgery  age  hospital_number rectal_temperature pulse respiratory_rate  \
0         1    1           534817               39.2    88               20   
1         2    1           530334               38.3    40               24   
2         1    9          5290409               39.1   164               84   
3         2    1           530255               37.3   104               35   
4         2    1           528355                NaN   NaN              NaN   
..      ...  ...              ...                ...   ...              ...   
288       1    1           529126                 38    50               36   
289       2    1           535054               38.6    45               16   
290       1    1           528890               38.9    80               44   
291       1    1           530034                 37    66               20   
292       1    1           534004                NaN    78               24   

    temperature_of_extremities peripheral_pulse capillary_refill_time pain  \
0                          NaN              NaN                     1    3   
1                            1                1                     1    3   
2                            4                1                     2    2   
3                          NaN              NaN                     2  NaN   
4                            2                1                     1    2   
..                         ...              ...                   ...  ...   
288                        NaN                1                     1    3   
289                          2                1                     1    1   
290                          3                3                     1    2   
291                          1                3                     1    4   
292                          3                3                     1  NaN   

     ... rectal_examination_feces packed_cell_volume total_protein  \
0    ...                        4                 50            85   
1    ...                        1                 33           6.7   
2    ...                        3                 48           7.2   
3    ...                      NaN                 74           7.4   
4    ...                        3                NaN           NaN   
..   ...                      ...                ...           ...   
288  ...                        3                 39           6.6   
289  ...                        1                 43            58   
290  ...                        3                 54           6.5   
291  ...                        1                 35           6.9   
292  ...                      NaN                 43            62   

    abdominocentesis_total_protein lesion_site lesion_type lesion_subtype  \
0                                2        2208           0              0   
1                              NaN           0           0              0   
2                              5.3        2208           0              0   
3                              NaN        4300           0              0   
4                              NaN           0           0              0   
..                             ...         ...         ...            ...   
288                            5.3        8400           0              0   
289                            NaN           0           0              0   
290                            NaN        7111           0              0   
291                            NaN       31110           0              0   
292                              2        2209           0              0   

    PossibleY PossibleY2  PossibleY3  
0           2          3           2  
1           1          1           2  
2           1          2           1  
3           2          2           2  
4           2          1           2  
..        ...        ...         ...  
288         1          1           1  
289         2          1           2  
2

Now see the null values and do the appropriate task for fillling the data or drop it.

In [524]:
df.isnull().sum()

surgery                             1
age                                 0
hospital_number                     0
rectal_temperature                 59
pulse                              24
respiratory_rate                   58
temperature_of_extremities         55
peripheral_pulse                   67
capillary_refill_time              31
pain                               54
peristalsis                        43
abdominal_distension               54
nasogastric_tube                  100
nasogastric_reflux                102
nasogastric_reflux_ph             240
rectal_examination_feces          101
packed_cell_volume                 29
total_protein                      32
abdominocentesis_total_protein    194
lesion_site                         0
lesion_type                         0
lesion_subtype                      0
PossibleY                           0
PossibleY2                          1
PossibleY3                          0
dtype: int64

In [525]:
df.shape

(293, 25)

We came to know that some of the rows are having null values more than half of the whole dataset. So we can drop them. The rest we will replace it with the mean or median or most frequent(mode).

In [526]:
for column in df.columns:
    if df[column].isnull().sum() > 70:
        df = df.drop(column, axis=1)
        print(column, "Dropped!")

df.isnull().sum()

nasogastric_tube Dropped!
nasogastric_reflux Dropped!
nasogastric_reflux_ph Dropped!
rectal_examination_feces Dropped!
abdominocentesis_total_protein Dropped!


surgery                        1
age                            0
hospital_number                0
rectal_temperature            59
pulse                         24
respiratory_rate              58
temperature_of_extremities    55
peripheral_pulse              67
capillary_refill_time         31
pain                          54
peristalsis                   43
abdominal_distension          54
packed_cell_volume            29
total_protein                 32
lesion_site                    0
lesion_type                    0
lesion_subtype                 0
PossibleY                      0
PossibleY2                     1
PossibleY3                     0
dtype: int64

Now the columns which have more than 70 null values are removed. They do not contribut much to our model. Now replace the null values with the median in every column.

In [527]:
for column in df.columns:
    x_median = df[column].median()
    df[column] = df[column].fillna(x_median)

df.isnull().sum()

surgery                       0
age                           0
hospital_number               0
rectal_temperature            0
pulse                         0
respiratory_rate              0
temperature_of_extremities    0
peripheral_pulse              0
capillary_refill_time         0
pain                          0
peristalsis                   0
abdominal_distension          0
packed_cell_volume            0
total_protein                 0
lesion_site                   0
lesion_type                   0
lesion_subtype                0
PossibleY                     0
PossibleY2                    0
PossibleY3                    0
dtype: int64

In [528]:
df.shape

(293, 20)

Now all the null dataset are cleared. Now lets find the correlation of the dataset.

In [529]:
df.corr()
df.shape

(293, 20)

In [530]:
#Normalize

from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
df_1 = df.drop('PossibleY', axis=1)
std_df = scalar.fit_transform(df)
df_std = pd.DataFrame(std_df, columns=df.columns)

In [552]:
df_std.shape

(293, 20)

In [531]:
X = df_std.drop('PossibleY', axis=1)
y = df['PossibleY']


From the correlation matrix, we didn't find any revelent correlation amoung the features. Lets visualize and see once more.

In [532]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Decision Tree for 1st variable

In [533]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report

clf = DecisionTreeClassifier(criterion='entropy', max_depth=9)

clf.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=9)

In [534]:
predicted_dt = clf.predict(X_train)
print("Accuracy for training set : ", (accuracy_score(y_train, predicted_dt)))


Accuracy for training set :  0.9316239316239316


In [535]:
confusion_matrix(y_train, predicted_dt)

array([[ 80,   0],
       [ 16, 138]])

In [536]:
print(classification_report(y_train, predicted_dt))

              precision    recall  f1-score   support

           1       0.83      1.00      0.91        80
           2       1.00      0.90      0.95       154

    accuracy                           0.93       234
   macro avg       0.92      0.95      0.93       234
weighted avg       0.94      0.93      0.93       234



In [537]:
from sklearn.metrics import accuracy_score

y_pred = clf.predict(X_test)
print("Accuracy for testing set", accuracy_score(y_test, y_pred))


Accuracy for testing set 0.7627118644067796


In [538]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[14,  3],
       [11, 31]])

In [539]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.56      0.82      0.67        17
           2       0.91      0.74      0.82        42

    accuracy                           0.76        59
   macro avg       0.74      0.78      0.74        59
weighted avg       0.81      0.76      0.77        59



# SVM for 1st variable

In [540]:
from sklearn.svm import SVC 

svc_clf = SVC(kernel='poly')

svc_clf.fit(X_train, y_train)

SVC()

In [541]:
predicted = svc_clf.predict(X_train)
print("Accuracy for training set : ", (accuracy_score(y_train, predicted)))

Accuracy for training set :  0.7991452991452992


In [542]:
confusion_matrix(y_train, predicted)

array([[ 35,  45],
       [  2, 152]])

In [543]:
print(classification_report(y_train, predicted))

              precision    recall  f1-score   support

           1       0.95      0.44      0.60        80
           2       0.77      0.99      0.87       154

    accuracy                           0.80       234
   macro avg       0.86      0.71      0.73       234
weighted avg       0.83      0.80      0.77       234



In [544]:
y_pred = svc_clf.predict(X_test)
print("Accuracy for testing set : ", accuracy_score(y_test, y_pred))

Accuracy for testing set :  0.7457627118644068


In [545]:
confusion_matrix(y_test, y_pred)

array([[ 3, 14],
       [ 1, 41]])

In [546]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.75      0.18      0.29        17
           2       0.75      0.98      0.85        42

    accuracy                           0.75        59
   macro avg       0.75      0.58      0.57        59
weighted avg       0.75      0.75      0.68        59



# Taking PossibleY3 as the target

In [547]:
# Normalizing
std_df = scalar.fit_transform(df)
df_std = pd.DataFrame(std_df, columns=df.columns)
X = df_std.drop('PossibleY3', axis=1)
y = df['PossibleY3']


# Splitting dataset

In [548]:
X_train_dt, X_test_dt, y_train_dt, y_test_dt = train_test_split(X, y, test_size=0.2, random_state=42)

# Decision Tree for 2nd variable

In [549]:
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(max_depth=7, criterion='entropy')

dt_clf.fit(X_train_dt, y_train_dt)

DecisionTreeClassifier(criterion='entropy', max_depth=7)

In [550]:
predicted_dt2 = svc_clf.predict(X_train_dt)
print("Accuracy for training set : ", (accuracy_score(y_train_dt, predicted_dt2)))

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- PossibleY
Feature names seen at fit time, yet now missing:
- PossibleY3


In [ ]:
confusion_matrix(y_train_dt, predicted_dt2)

array([[140,   7],
       [ 17,  70]])

In [ ]:
print(classification_report(y_train_dt, predicted_dt2))

              precision    recall  f1-score   support

           1       0.89      0.95      0.92       147
           2       0.91      0.80      0.85        87

    accuracy                           0.90       234
   macro avg       0.90      0.88      0.89       234
weighted avg       0.90      0.90      0.90       234



In [ ]:
y_pred_dt = dt_clf.predict(X_test)
print("Accuracy for testing set : ", accuracy_score(y_test_dt, y_pred_dt))

Accuracy for testing set :  0.9152542372881356


In [ ]:
print(confusion_matrix(y_test_dt, y_pred_dt))


[[38  3]
 [ 2 16]]


In [ ]:
print(classification_report(y_test_dt, y_pred_dt))

              precision    recall  f1-score   support

           1       0.95      0.93      0.94        41
           2       0.84      0.89      0.86        18

    accuracy                           0.92        59
   macro avg       0.90      0.91      0.90        59
weighted avg       0.92      0.92      0.92        59



# SVM for 2nd variable

In [ ]:
svc_clf2 = SVC(kernel='linear')
svc_clf2.fit(X_train_dt, y_train_dt)


SVC(kernel='linear')

In [ ]:
predicted_svc = svc_clf.predict(X_train_dt)
print("Accuracy for training set : ", (accuracy_score(y_train_dt, predicted_svc)))

Accuracy for training set :  0.8974358974358975


In [ ]:
confusion_matrix(y_train_dt, predicted_svc)

array([[140,   7],
       [ 17,  70]])

In [ ]:
print(classification_report(y_train_dt, predicted_svc))

              precision    recall  f1-score   support

           1       0.89      0.95      0.92       147
           2       0.91      0.80      0.85        87

    accuracy                           0.90       234
   macro avg       0.90      0.88      0.89       234
weighted avg       0.90      0.90      0.90       234



In [ ]:
y_perd_svc2 = svc_clf.predict(X_test_dt)
print("Accuracy for testing set : ", accuracy_score(y_test, y_perd_svc2))

Accuracy for testing set :  0.8983050847457628


In [ ]:
confusion_matrix(y_test_dt, y_perd_svc2)

array([[40,  1],
       [ 5, 13]])

In [ ]:
print(classification_report(y_test_dt, y_perd_svc2))

              precision    recall  f1-score   support

           1       0.89      0.98      0.93        41
           2       0.93      0.72      0.81        18

    accuracy                           0.90        59
   macro avg       0.91      0.85      0.87        59
weighted avg       0.90      0.90      0.89        59

